### ISSUE TITLE
Integration with Grafana Agent for Windows

### ISSUE THREAD

**Issue by oriondvd** [nickbabcock/OhmGraphite#240]
Can anyone help me integrate OhmGraphite with [Grafana Agent for Windows](https://grafana.com/blog/2021/04/22/weve-added-first-class-windows-support-to-grafana-agent/)?
I've installed OhmGraphite and can see metrics here - http://localhost:4445/metrics
But I don't know how to configure Grafana Agent's configuration file - C:\Program Files\Grafana Agent\agent-config.yaml - https://grafana.com/docs/agent/latest/configuration/
Here my configuration file now, I can see windows_exporter metrics (http://localhost:12345/integrations/windows_exporter/metrics), but there is no OhmGraphite metrics:
```
server:
  http_listen_port: 12345
prometheus:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 15s
    remote_write:
    - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
      basic_auth:
        username: LOGIN
        password: PASS
  configs:
    - name: integrations
    - name: ohmgraphite
      host_filter: false
      scrape_configs:
        - job_name: ohmgraphite
          static_configs:
          - targets: ['localhost:4445']
integrations:
  windows_exporter:
    enabled: true
```
What I've missing?
