### ISSUE TITLE
More flexible hdd data metrics

### ISSUE THREAD

**Issue by roy-spark** [nickbabcock/OhmGraphite#388]
Maybe this is not an issue but i can't find a way to predict based on current hdd growth (percent sure, but it's not as flexible) so that I would be able to set an alarm such as the ones able to set in windows exporters and node exporter.

The code below might not be fully correct but it is to show the concept.

``` 
  - alert: DiskFilling
    expr: 100 * (windows_logical_disk_free_bytes / windows_logical_disk_size_bytes) < 15 and predict_linear(windows_logical_disk_free_bytes[6h], 4 * 24 * 3600) < 0
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Disk full in four days (instance {{ $labels.instance }})"
      description: "{{ $labels.volume }} is expected to fill up within four days. Currently {{ $value | humanize }}% is available.\n VALUE = {{ $value }}\n LABELS: {{ $labels }}"
```

If the case is that it is not possible to make such alerts atm then there is good reason to add it imho. I can do it if you are not up for it.
