### ISSUE TITLE
incorrect battery values

### ISSUE THREAD

**Issue by FelixChial** [nickbabcock/OhmGraphite#444]
- LHM 0.9.3
- Graphite 0.32.0

LHM reports correct values but OHM just stays at 99%, 13v, 37.4Wh, etc
dunno if its relevant but it runs as a service with prometheus output
values change sometimes but then stay the same for days
other metrics work fine 🤔 

### graphs over the last two days
![ohm-battery1](https://github.com/nickbabcock/OhmGraphite/assets/29210187/66d7382d-93bf-4053-b5f2-b977d279faf9)
### graphs over the last 14 days
i think drop at around 03/16 - 03/18 is related to upgrade from 0.31.0 to 0.32.0
![ohm-battery3](https://github.com/nickbabcock/OhmGraphite/assets/29210187/f7f3b988-2943-4811-aa85-55f9cca1f08c)
### metrics sample
![ohm-battery2](https://github.com/nickbabcock/OhmGraphite/assets/29210187/e9af4cfb-4643-454d-84a7-34e636495616)

### configs
prometheus
```yml
global:
  scrape_interval: 15s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'ohm-cobra'
    static_configs:
      - targets: ['192.168.191.103:4445']
```
graphite
```xml
﻿<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="type" value="prometheus" />
    <add key="prometheus_port" value="4445" />

    <!-- This is the host that OhmGraphite listens on.
         `*` means that it will listen on all interfaces.
         Consider restricting to a given IP address -->
    <add key="prometheus_host" value="192.168.191.103" />
    <add key="prometheus_path" value="metrics/" />
  </appSettings>
</configuration>
```
